POST http://localhost:8080/createEvent
content-type: application/application/json

{
  "Name": "Tech Innovators Summit",
  "Description": "A premier event showcasing cutting-edge technology, startups, and groundbreaking innovations in the tech industry.",
  "Location": "San Francisco Marriott Marquis"
}
