POST http://localhost:8080/create-event
content-type: application/application/json

{
  "Name": "Comic Con Festival",
  "Description": "A fun-filled event featuring the best standup comedians, live performances, and entertainment.",
  "Location": "Los Angeles Convention Center"
}
